### ISSUE TITLE
Grid View Layout Issue

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/tc-site#270]
Description
-----------------------------------------------------------------
Grid View Layout Issue

Steps to Reproduce
-----------------------------------------------------------------

- Open the site
- Login as a valid user
- In the 'challenges' page
- Go to Grid View

Expected Result(s)
-----------------------------------------------------------------
- Must display 3 items in each row

Actual Result
-----------------------------------------------------------------
- Grid View Layout Issue

Environment
-----------------------------------------------------------------
- **Browser(s):** Chrome 52.0.2743.82 m, FF 47.0.1, IE11
- **Operating System:** Windows 7 Pro 64bit

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![1](https://cloud.githubusercontent.com/assets/4592712/17066118/309b9b7a-5063-11e6-9419-444008eb20b1.png)

**Comment by tladendo** [comment]
not specific to "members" subdomain
