### ISSUE TITLE
If the submission count is '0'; it is not displaying in the tool tip

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/tc-site#272]
Description
-----------------------------------------------------------------
If the submission count is '0'; it is not displaying in the tool tip

Steps to Reproduce
-----------------------------------------------------------------

- Open the site
- Login as a valid user
- In the 'challenges' page
- Go to Grid View
- Hover over the 0 submission 

Expected Result(s)
-----------------------------------------------------------------
- Must display 0 in the tool tip

Actual Result
-----------------------------------------------------------------
- If the submission count is '0'; it is not displaying in the tool tip

Environment
-----------------------------------------------------------------
- **Browser(s):** Chrome 52.0.2743.82 m, FF 47.0.1, IE11
- **Operating System:** Windows 7 Pro 64bit

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![2](https://cloud.githubusercontent.com/assets/4592712/17066136/40a746a4-5063-11e6-9e72-3e1fdcf8294b.png)

**Comment by tladendo** [comment]
this is not unique to the "members" subdomain
