### ISSUE TITLE
Website not loading blog feed

### ISSUE THREAD

**Issue by Colinh84** [appirio-tech/tc-site#273]
The test website is not correctly loading the blogfeed.

Browser: Chrome 51 on Windows 10

**Steps:**
- Visit test website in Chrome
- Scroll down page, notice blog feed is missing compared to non-subdomain test site.
- Open chrome inspector and switch to console
- see error

**Expected:**
- Blog feed should be present as in non-subdomain site.

**Actual:**
- Error in console from raven.js unable to load blogfeed.

**Screenshot:**
http://imgur.com/959fWpo.png

**Comment by tladendo** [comment]
dashboard page is out of scope
