### ISSUE TITLE
Project Timeline: Project timeline should be editable 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/tc-site#274]
Project Timeline: Project timeline should be editable 
.
Steps to reproduce:
1.) Launch the Application
2.)Login with user name  sweta.singh
3.) Create a project
4.) go to  project timeline

Expected Result:timeline should be editable

Actual Result:not editable
Environment: Windows 7, Chrome 51

![image](https://cloud.githubusercontent.com/assets/16131461/17060636/81e6e090-5048-11e6-83d9-f7ec30080205.png)

**Comment by tladendo** [comment]
"connect.topcoder" is outside of scope
