### ISSUE TITLE
[Challenges] Layout Issue in the 'Submission End Date Range' Date time pickers

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/tc-site#275]
Description
-----------------------------------------------------------------
[Challenges] Layout Issue in the 'Submission End Date Range' Date time pickers

Steps to Reproduce
-----------------------------------------------------------------

- Open the site
- Login as a valid user
- In the 'challenges' page
- Go to Grid View
- Go to Design Challenges
- Open the Submission End Date Range

Expected Result(s)
-----------------------------------------------------------------
- DTP boxes must display within the Box

Actual Result
-----------------------------------------------------------------
- Layout Issue in the 'Submission End Date Range' Date time pickers

Environment
-----------------------------------------------------------------
- **Browser(s):** Chrome 52.0.2743.82 m, FF 47.0.1, IE11
- **Operating System:** Windows 7 Pro 64bit

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![3](https://cloud.githubusercontent.com/assets/4592712/17066138/45d99550-5063-11e6-8d7e-fda06ef4c98f.png)

**Comment by tladendo** [comment]
not unique to "members" subdomain
