### ISSUE TITLE
time zone not shown properly 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/tc-site#276]
Steps to reproduce
-------------
     Goto https://members.topcoder-dev.com/challenges/?pageIndex=1
     See  TimeLine 

Expected results
-------------
   time should  show  time zone properly  
Current results
-------------------
Time zone not shown properly  properly 

![2016-07-22_2010](https://cloud.githubusercontent.com/assets/3225433/17060716/ecad4ef0-5048-11e6-9179-0e7fabab8795.png)

**Comment by tladendo** [comment]
couldn't reproduce, if you can provide more information i'll take another look
