### ISSUE TITLE
Create Project: on selecting platform as  Other (Incl. non-app work), other option should not be disable  

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/tc-site#277]
Create Project: on selecting platform as  Other (Incl. non-app work), other option should not be disable .

Steps to reproduce:
1.) Launch the Application
2.)Login with user name  sweta.singh
3.) Click on Projects
4.) Create new project
5.) Enter project name
6.) Select plateform as Other (Incl. non-app work),

Expected Result: other platform option should be select-able 

Actual Result: all option disable to select 

Environment: Windows 7, Chrome 51

![image](https://cloud.githubusercontent.com/assets/16131461/17060776/2b0be9f4-5049-11e6-8ede-3832b0330aff.png)

**Comment by tladendo** [comment]
this page is out of scope
