### ISSUE TITLE
[Challenges] Save My Search is not working

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/tc-site#278]
Description
-----------------------------------------------------------------
[Challenges] Save My Search is not working

Steps to Reproduce
-----------------------------------------------------------------

- Open the site
- Login as a valid user
- In the 'challenges' page
- Go to Grid View
- Go to Design Challenges
- Filter a Challenge (eg: Logo Design)
- Click SAVE
- Enter a Name
- Click Save My Search
- Now click on the My Filters drop down

Expected Result(s)
-----------------------------------------------------------------
- Must display the saved search in the list

Actual Result
-----------------------------------------------------------------
- Save My Search is not working

Environment
-----------------------------------------------------------------
- **Browser(s):** Chrome 52.0.2743.82 m, FF 47.0.1, IE11
- **Operating System:** Windows 7 Pro 64bit

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![4](https://cloud.githubusercontent.com/assets/4592712/17066174/6f96ed3e-5063-11e6-882c-0cfff49701b9.png)

**Comment by tladendo** [comment]
not unique to "members" subdomain
