### ISSUE TITLE
challenge type layout issue 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/tc-site#280]
Steps to reproduce
-------------
     Goto https://www.topcoder-dev.com/challenges/develop/active/?pageIndex=1
    See 5 or more tages challenge types 
![2016-07-22_2020](https://cloud.githubusercontent.com/assets/3225433/17061048/3ff41890-504a-11e6-8c5a-f482d7ab0c78.png)

Expected results
-------------
  Should show properly 
Current results
-------------------
   challenge type is  not showing  properly 

Environment
-------------------
    Browser(s):FF 47.0.1
    Operating System: Windows 8.1

**Comment by tladendo** [comment]
not unique to "members" subdomain
