### ISSUE TITLE
Challenges> Result: message should be correct "Result are available after the review phase."

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/tc-site#282]
Challenges> Result: message should be correct "Result are available after the review phase.".

Steps to reproduce:
1.) Launch the Application
2.)Login with valid user name 
3.) Go to Challenges 
4.) Go to Challenges detail page
5.) CLick on Result tab

Expected Result: message should be "Result are available after the review phase."

Actual Result: message is Submission are available after the review phase.

Environment: Windows 7, Chrome 51

![image](https://cloud.githubusercontent.com/assets/16131461/17061176/ef020810-504a-11e6-8f46-e670ed2ff924.png)

**Comment by tladendo** [comment]
not specific to "members" subdomain
