### ISSUE TITLE
Grid layout issue 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/tc-site#283]
Steps to reproduce
-------------
     Goto  https://members.topcoder-dev.com/challenges/?pageIndex=1
     Click All challenges
     Click Grid type 
     See 
![2016-07-22_2026](https://cloud.githubusercontent.com/assets/3225433/17061148/c6b869d0-504a-11e6-84b2-958388c152d2.png)
 

Expected results
-------------
   must show properly 
Current results
-------------------
   Grid layout is changed based on challenge types 
Environment
-------------------
Browser(s):FF 47.0.1
Operating System: Windows 8.1

**Comment by tladendo** [comment]
not unique to "members" subdomain
