### ISSUE TITLE
[Challenges] Clicking 'View All' will stuck the site

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/tc-site#284]
Description
-----------------------------------------------------------------
[Challenges] Clicking 'View All' will stuck the site

Steps to Reproduce
-----------------------------------------------------------------

- Open the site
- Login as a valid user
- In the 'challenges' page
- Go to Grid View
- Go to Development Challenges
- Scroll down and click 'View All' from the pagination

Expected Result(s)
-----------------------------------------------------------------
- Must load all the challenges without freezing the site

Actual Result
-----------------------------------------------------------------
- Clicking 'View All' will stuck the site

Environment
-----------------------------------------------------------------
- **Browser(s):** Chrome 52.0.2743.82 m, FF 47.0.1, IE11
- **Operating System:** Windows 7 Pro 64bit

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![5](https://cloud.githubusercontent.com/assets/4592712/17066176/71b60abe-5063-11e6-8fc2-82a22fdfd426.png)

**Comment by tladendo** [comment]
not unique to "members" subdomain
