### ISSUE TITLE
Data Science Challenges: broken images on data science challenges page

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/tc-site#285]
Data Science Challenges: broken images on data science challenges page.

Steps to reproduce:
1.) Launch the Application
2.)Login with user name 
3.) Go to data science Challenges 
Expected Result: image should visible

Actual Result: broken images

Environment: Windows 7, Chrome 51

![image](https://cloud.githubusercontent.com/assets/16131461/17061258/459ca982-504b-11e6-81df-f066440f6144.png)

**Comment by tladendo** [comment]
this page is outside of scope
