### ISSUE TITLE
[Common] [Challenges] Complete Challenge name is not displayed

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/tc-site#286]
Description
-----------------------------------------------------------------
[Challenges] Complete Challenge name is not displayed

Steps to Reproduce
-----------------------------------------------------------------

- Open the site
- Login as a valid user
- In the 'challenges' page
- Go to Grid View
- Go to Development Challenges
- Goto Page 4
- Check the last row second item (/challenge-details/30048991/?type=develop)
- "Hercules OnCampus Web Application - NGB Album art issue {COAM-1267}"

Expected Result(s)
-----------------------------------------------------------------
- Complete Challenge name is not displayed, If not must display (...) at the end

Actual Result
-----------------------------------------------------------------
- Complete Challenge name is not displayed

Environment
-----------------------------------------------------------------
- **Browser(s):** Chrome 52.0.2743.82 m, FF 47.0.1, IE11
- **Operating System:** Windows 7 Pro 64bit

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![6](https://cloud.githubusercontent.com/assets/4592712/17066199/9dd62ade-5063-11e6-9daa-a68bbfcceade.png)

**Comment by tladendo** [comment]
not unique to "members" subdomain
