### ISSUE TITLE
[Challenges] 'Queue' link is not working in 'DATA SCIENCE CHALLENGES'

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/tc-site#287]
Description
-----------------------------------------------------------------
[Challenges] 'Queue' link is not working in 'DATA SCIENCE CHALLENGES'

Steps to Reproduce
-----------------------------------------------------------------

- Open the site
- Login as a valid user
- In the 'challenges' page
- Go to Grid View
- Go to DATA SCIENCE CHALLENGES Challenges
- Click 'Queue' link

Expected Result(s)
-----------------------------------------------------------------
- Must work the link

Actual Result
-----------------------------------------------------------------
- 'Queue' link is not working in 'DATA SCIENCE CHALLENGES'

Environment
-----------------------------------------------------------------
- **Browser(s):** Chrome 52.0.2743.82 m, FF 47.0.1, IE11
- **Operating System:** Windows 7 Pro 64bit

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![7](https://cloud.githubusercontent.com/assets/4592712/17066224/b7d43df4-5063-11e6-8a8a-514d5120858d.png)

**Comment by tladendo** [comment]
not unique to "members" subdomain
