### ISSUE TITLE
Submission End date Range: searching with defined date(today, 7 days) range not working

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/tc-site#288]
Submission End date Range: searching with defined date(today, 7 days) range not working.

Steps to reproduce:
1.) Launch the Application
2.)Login with user name 
3.) Go to Challenges 
4.) Go to Submission End date Range
5.) Select date range as 7 days 

Expected Result: search should work

Actual Result: searching not working

Environment: Windows 7, Chrome 51

![image](https://cloud.githubusercontent.com/assets/16131461/17061380/db49dda6-504b-11e6-91a2-5089c6429c17.png)

**Comment by tladendo** [comment]
is this specific to the "members" subdomain?
