### ISSUE TITLE
[Challenges] RSS Links are not working

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/tc-site#289]
Description
-----------------------------------------------------------------
[Challenges] RSS Links are not working

Steps to Reproduce
-----------------------------------------------------------------

- Open the site
- Login as a valid user
- In the 'challenges' page
- Go to Grid View
- Go to GRAPHIC DESIGN CHALLENGES
- Click 'RSS' link

Expected Result(s)
-----------------------------------------------------------------
- Must display the RSS Links

Actual Result
-----------------------------------------------------------------
- RSS Links are not working

Environment
-----------------------------------------------------------------
- **Browser(s):** Chrome 52.0.2743.82 m, FF 47.0.1, IE11
- **Operating System:** Windows 7 Pro 64bit

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by tladendo** [comment]
is this specific to the "members" subdomain?

**Comment by sdgun** [comment]
![8](https://cloud.githubusercontent.com/assets/4592712/17066273/efe510ba-5063-11e6-8998-3ab9c14010ea.png)

**Comment by sdgun** [comment]
@tladendo No
