### ISSUE TITLE
Share: showing some non-understandable strings  on sharing at facebook

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/tc-site#290]
Share: showing some non-understandable strings  on sharing at facebook

Steps to reproduce:
1.) Launch the Application
2.)Login with user name 
3.) Go to challenge detail page
4.) Go to share links
5.) share on Facebook

Expected Result: should display some understandable message 

Actual Result:showing some html type code

Environment: Windows 7, Chrome 51

![image](https://cloud.githubusercontent.com/assets/16131461/17061679/57eac004-504d-11e6-9de4-67f125fdeddd.png)

**Comment by tladendo** [comment]
please see https://apps.topcoder.com/forums/?module=Thread&threadID=888535&start=0
