### ISSUE TITLE
design Challenges : CHECKPOINT WINNERS showing the hand icon on hovering the mouse , but on clicking redirecting to no where 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/tc-site#292]
design Challenges : CHECKPOINT WINNERS showing the hand icon on hovering the mouse , but on clicking redirecting to no where .

Steps to reproduce:
1.) Launch the Application
2.)Login with user name 
3.) go to Design challenges
4.) open challenges https://www.topcoder-dev.com/challenge-details/30048171/?type=design
5.) Go to check point winners
6.) Hover the mouse
Expected Result: should not visible hand icon or link should redirect to winner profile

Actual Result: showing hand icon
Environment: Windows 7, Chrome 51

**Comment by tladendo** [comment]
should provide instructions to contrast w/ "members" subdomain. see https://apps.topcoder.com/forums/?module=Thread&threadID=888535&start=0
