### ISSUE TITLE
[Challenges]layout issue when resize

### ISSUE THREAD

**Issue by Twiknight** [appirio-tech/tc-site#293]
1. Steps

    1. Go to the front page
    2. resize your browser to 560 * 920 

2. screenshot
![image](https://cloud.githubusercontent.com/assets/11556597/17061822/f5cd4aac-5062-11e6-8bb3-749c464ab0cb.png)

3. expectation

The community login button should not show

4. current results

It shows and covers the current page

5. Browser/platform
windows 10 10586
chrome 51.0.2704.103 m

**Comment by tladendo** [comment]
please see https://apps.topcoder.com/forums/?module=Thread&threadID=888535&start=0
