### ISSUE TITLE
 Subscribe to Challenges not working

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/tc-site#294]
Subscribe to Challenges not working.clicking on subscribe to challenges redirecting to broken page title names "Open undefined"

Steps to reproduce:
1.) Launch the Application
2.)Login with user name 
3.) go to development challenges
4.) click on Subscribe to challenges

Expected Result:should work

Actual Result: redirecting to broken page title names "Open undefined"

Environment: Windows 7, Chrome 51

![image](https://cloud.githubusercontent.com/assets/16131461/17062125/4679573e-504f-11e6-9912-9f6d1716fbee.png)

![image](https://cloud.githubusercontent.com/assets/16131461/17062152/66b3bae4-504f-11e6-8755-61405d7e9dba.png)

**Comment by tladendo** [comment]
can't reproduce, please notify me if this was something unique to the "members" subdomain
