### ISSUE TITLE
Wrong link on My SRMs page

### ISSUE THREAD

**Issue by Colinh84** [appirio-tech/tc-site#297]
at the link https://members.topcoder-dev.com/my-srms/, if you click the "find SRMs" button you are redirected to the old challenge listings page instead of the new members subdomain challenge listing page.

Browser: Chrome 51 on Windows 10

**Steps:**
- Visit member.topcoder-dev.com test website in Chrome, login
- Go to https://members.topcoder-dev.com/my-srms/
- Click "find SRMs"
- link does not go to members subdomain challenge listings

**Expected:**
- link should go to the challenge listing on the members subdomain

**Actual:**
- link goes to old www subdomain listing page.

**Screenshot:**
http://i.imgur.com/KApNa81.png

**Comment by tladendo** [comment]
page is out of scope
