### ISSUE TITLE
Wrong links on dashboard page

### ISSUE THREAD

**Issue by Colinh84** [appirio-tech/tc-site#300]
On the main dashboard page for logged in members at: https://members.topcoder-dev.com/my-dashboard/ the first section of the page contains links to the old www section of the website instead of the new members subdomain through the "get started" and "find challenges" buttons.

Browser: Chrome 51 on Windows 10

**Steps:**
- Visit https://members.topcoder-dev.com/my-dashboard/ test website in Chrome, login
- In main section of dashboard page, "get started" and find challenges" links lead to old pages instead of new members subdomain. Both these links are correct in the upper nav but not in this section of the site.

**Expected:**
- link should go to the challenge listing or getting started pages on the members subdomain

**Actual:**
- link goes to old www subdomain listing page.

**Screenshot:**
http://imgur.com/yksyxHf.png

**Comment by tladendo** [comment]
out of scope
