### ISSUE TITLE
[Challenges] Clicking on Browser back button won't load the challenges

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/tc-site#301]
Description
-----------------------------------------------------------------
[Challenges] Clicking on Browser back button won't load the challenges

Steps to Reproduce
-----------------------------------------------------------------

- Open the site (https://members.topcoder-dev.com)
- Login as a valid user
- In the 'challenges' page
- Go to Grid View
- Go to SOFTWARE DEVELOPMENT CHALLENGES
- Click 'Past Challenges'
- Filter the Data from 'Android' and ActionScript'
- You can see only one challenge (eg: Peer Review - Troubleshooting user able to review own submission)
- Click on this challenge
- Click Browser back button
- Check the challenge listing page

- Here; it loads the challenge: https://www.topcoder-dev.com/challenges/develop/past/?startDate=2015-07-31&technologies=ActionScript&platforms=Android&pageIndex=1
- Here it won't: https://members.topcoder-dev.com/challenges/develop/past/?startDate=2015-07-31&technologies=ActionScript&platforms=Android&pageIndex=1

Expected Result(s)
-----------------------------------------------------------------
- Must load the challenges

Actual Result
-----------------------------------------------------------------
- Clicking on Browser back button won't load the challenges

Environment
-----------------------------------------------------------------
- **Browser(s):** Chrome 52.0.2743.82 m
- **Operating System:** Windows 7 Pro 64bit

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by tladendo** [comment]
i see the same bug on "www" though it's inconsistent for both subdomains
