### ISSUE TITLE
Past challenges visible in Open challenges & current phase status also not changed

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/tc-site#303]
Past challenges visible in Open challenges & current phase status also not changed

Steps to reproduce:
1.) Launch the Application
2.)Login with user name 
3.) go to Open challenges 
4.) in the list project with start date as 22 jan , 2016 & submitted date as Feb 21, 2016 07:25 EST showing in active list

Expected Result: project should not display in active list

Actual Result:past project display in active grid

Environment: Windows 7, Chrome 51

![image](https://cloud.githubusercontent.com/assets/16131461/17063074/3915e554-5053-11e6-83bb-e3afbf44162e.png)

**Comment by tladendo** [comment]
not specific to "members" subdomain
