### ISSUE TITLE
calendar  view-Data not loading 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/tc-site#305]
Steps to reproduce
-------------
     Goto https://members.topcoder-dev.com/challenges/data/calendar/
    Goto  https://www.topcoder-dev.com/challenges/data/calendar/
    See  In calendar view  data not loading  on  https://www.topcoder-dev.com/challenges/data/calendar/
Expected results
-------------
    must show all data properly 
Current results
-------------------
   Data not loading   properly  on https://www.topcoder-dev.com/challenges/data/calendar/

![2016-07-22_2129](https://cloud.githubusercontent.com/assets/3225433/17063183/abac43d8-5053-11e6-8075-4dd2723464ff.png)
![2016-07-22_2129_001](https://cloud.githubusercontent.com/assets/3225433/17063184/abe96c86-5053-11e6-9f84-dc3ba8bfe0c1.png)

Environment
-------------------
    Browser:  FF 47.0.1
    Operating System: Windows 8.1

**Comment by tladendo** [comment]
can't reproduce. what are you comparing this with? and what's unique to the "members" subdomain?
