### ISSUE TITLE
Design Challenges : After the registration Text link  " Registrants & Submissions" display as "Registrant | Submissions"

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/tc-site#308]
Design Challenges : After the registration Text link  " Registrants & Submissions" display as "Registrant | Submissions" and clicking on Submission showing the Result tab.

Steps to reproduce:
1.) Launch the Application
2.)Login with user name 
3.) Go to Design Challenges
4.) Register to challenges
5.) Go to Text Link Registrants & Submissions

Expected Result: should display as Registrants & Submissions

Actual Result: showing as Registrants | Submissions
Environment: Windows 7, Chrome 51

![image](https://cloud.githubusercontent.com/assets/16131461/17063561/9272aefa-5055-11e6-828e-f277e3c66233.png)

**Comment by tladendo** [comment]
this is how design challenges are supposed to be
