### ISSUE TITLE
Data Science : opening on project from the calendar view redirecting to Development type project detail

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/tc-site#309]
Design challenges : opening on project from the calendar view redirecting to Development type project detail.

Steps to reproduce:
1.) Launch the Application
2.)Login with user name 
3.) go to data science
4.) view project in calendar
5.) open the project

Expected Result:should redirect to data science type project
Actual Result: redirecting to development type project

Environment: Windows 7, Chrome 51

![image](https://cloud.githubusercontent.com/assets/16131461/17063802/b9df7026-5056-11e6-8ddb-472130ffc951.png)

**Comment by tladendo** [comment]
this is the desired behavior
