### ISSUE TITLE
Title is missing in the three categories (Design, Development, Data Science)

### ISSUE THREAD

**Issue by 3amrSaad** [appirio-tech/tc-site#310]
### Steps to Reproduce
1. Open Safari
2. Go to "https://www.topcoder-dev.com/challenges/develop/active/?pageIndex=1"
3. Go to "https://members.topcoder-dev.com/challenges/develop/active/?pageIndex=1" and Observe

### Expected Result(s)
Challenges Title should appear like the one in the second step.

### Actual Result
An empty space instead and the Challenges Title is missing.

### Environment
**Operating System:** MAC OS X (Mavericks), Version 10.9
**Browser:** Safari Version 7.0 (9537.71)
### Screenshots
See comments section.

**Comment by 3amrSaad** [comment]
http://icecream.me/b56b419724fab405592226bc8677099f

http://icecream.me/a01370c72e66538ee043d5e7905b5b19

**Comment by tladendo** [comment]
couldn't reproduce
