### ISSUE TITLE
challenge listing grid view tooltips are empty instead of displaying 0

### ISSUE THREAD

**Issue by Colinh84** [appirio-tech/tc-site#314]
On challenge listing page, click "grid view" and hover over the bottom bar of listings that display 0 for registrants or submissions, and an empty tooltip will display.

Browser: Chrome 51 on Windows 10

**Steps:**
- Visit https://members.topcoder-dev.com/challenges/develop/active/?pageIndex=1
- click "grid view" button
- Hover over the registrants or submissions icons on the bottom bar where 0 is displayed
- Empty tooltip is displayed

**Expected:**
- Tooltip should show 0 if there are 0 registrants or submissions

**Actual:**
- Tooltips are empty

**Screenshot:**
http://imgur.com/BFJgVPT.png

**Comment by tladendo** [comment]
not unique to "members" subdomain
