### ISSUE TITLE
Save search feature does not work on challenge listing pages

### ISSUE THREAD

**Issue by Colinh84** [appirio-tech/tc-site#316]
On challenge listing pages, selecting any search criteria from dropdowns and entering search terms, then clicking the save button on the right side does not properly save your search.

Browser: Chrome 51 on Windows 10

**Steps:**
- Visit https://members.topcoder-dev.com/challenges/develop/active/?pageIndex=1
- Enter a search term, and select any values from the dropdowns.
- After search loaded, click "Save" button under search box to the right side
- Enter search save name, click "Saev my search"
- Page looks like it is doing something, but subsequently clicking on the "My filters" dropdown shows "no saved searches found.", even after refreshing page.

**Expected:**
- Search should be saved in the "My Filters" dropdown

**Actual:**
- Search does not save, shows "no saved searches found"

**Screenshot:**
http://imgur.com/ZDSUA5z.png

**Comment by tladendo** [comment]
not unique to "members" subdomain
