### ISSUE TITLE
Results page  is different

### ISSUE THREAD

**Issue by kaygee1** [appirio-tech/tc-site#318]
Open pages

https://members.topcoder-dev.com/challenge-details/30049490/?type=design

https://www.topcoder-dev.com/challenge-details/30049490/?type=design

Tap on Results tab

actual - In topcoder - dev it displays - Submissions are available after the review phase.

In member.topcoder-dev it does't display anything

windows 10 Chrome 51

![13](https://cloud.githubusercontent.com/assets/5115050/17066292/013566e4-5064-11e6-8c64-a613d032de13.png)
![14](https://cloud.githubusercontent.com/assets/5115050/17066293/01392162-5064-11e6-8285-122616dc43ef.png)

**Comment by tladendo** [comment]
duplicate of #296
