### ISSUE TITLE
Info and prize details not displayed

### ISSUE THREAD

**Issue by kaygee1** [appirio-tech/tc-site#319]
Open pages

https://www.topcoder-dev.com/challenge-details/30049284/?type=develop

https://members.topcoder-dev.com/challenge-details/30049284/?type=develop

See the space next to the  first 3 steps

topcoder-dev - this place has some info with regards to details and prizes

member.topcoder-dev - this place has no info at all.

windows10 chrome 51

![15](https://cloud.githubusercontent.com/assets/5115050/17067861/7504d7ec-506b-11e6-82fb-59a04c527279.png)

![16](https://cloud.githubusercontent.com/assets/5115050/17067864/7932551a-506b-11e6-9bfd-f35a27b94066.png)

**Comment by tladendo** [comment]
duplicate #313
