### ISSUE TITLE
Compete, Learn, Community, Login Button and Join Button are missing from members.topcoder-dev's Header

### ISSUE THREAD

**Issue by 3amrSaad** [appirio-tech/tc-site#322]
### Steps to Reproduce
1. Open Firefox
2. Go to "https://www.topcoder-dev.com/challenge-details/30048886/?type=develop#viewRegistrant"
3. Go to "https://members.topcoder-dev.com/challenge-details/30048886/?type=develop#viewRegistrant" and Observe

### Expected Result(s)
Compete, Learn, Community, Login Button and Join Button should be displayed in the Header.

### Actual Result
An empty white space instead.

### Environment
**Operating System:** Ubuntu 15.10
**Browser:** Firefox Version 43.0.4
### Screenshots
See comments section.

**Comment by 3amrSaad** [comment]
http://icecream.me/97203b94beb6eb192d8b00d66349d7b1

http://icecream.me/bbd9fe52fc3211f900b1cc2c498d7af7

**Comment by tladendo** [comment]
this happens in www and isn't specific to "members"
