### ISSUE TITLE
Broken image on our data science listing page

### ISSUE THREAD

**Issue by vbaileytopcoder** [appirio-tech/tc-site#467]
https://www.screencast.com/t/esMOAOPeZCry

**Comment by birdofpreyru** [comment]
@vbaileytopcoder It is already noted here: https://github.com/appirio-tech/topcoder-app/issues/973
I'm not sure, though, what is the correct fix? To add the `TCO` version of the icon, or to show the standard icon no matter whether API says a data science challenge is tco-eligible or not?

**Comment by birdofpreyru** [comment]
Fixed in https://github.com/appirio-tech/topcoder-app/issues/973
