### ISSUE TITLE
Back button on submission page does not work

### ISSUE THREAD

**Issue by shubhendusaurabh** [appirio-tech/tc-site#476]
Back to active Challenge link on submission page does not work. It just updates the location path.
![back](https://cloud.githubusercontent.com/assets/1818387/23014656/db4110f0-f455-11e6-8ae3-b61484bfbc23.png)

cc @birdofpreyru

**Comment by vbaileytopcoder** [comment]
Can I close this one out @birdofpreyru

**Comment by birdofpreyru** [comment]
Yeap, it was fixed, but I've overlooked this ticket in this repo. Closing.
